export enum Permissions {
  MANAGE_REQUESTS = 'MANAGE_REQUESTS',
  MANAGE_USERS = 'MANAGE_USERS',
  MANAGE_ANIMALS = 'MANAGE_ANIMALS',
  ADD_ANIMALS = 'ADD_ANIMALS',
  ADD_PROTECTORS = 'ADD_PROTECTORS',
}
